-- +goose Up
-- Phase 2B：业务域服务 schema-per-service 拆分（2A audit 模式推广）
-- 每服务 schema + LIKE 拷贝独属表，数据双份保留（public 副本作回滚点）。

CREATE SCHEMA IF NOT EXISTS ai_svc;
CREATE TABLE IF NOT EXISTS ai_svc.ai_conversations (LIKE public.ai_conversations INCLUDING ALL);
INSERT INTO ai_svc.ai_conversations SELECT * FROM public.ai_conversations ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.ai_conversations', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.ai_conversations), 1));
CREATE TABLE IF NOT EXISTS ai_svc.ai_document_chunks (LIKE public.ai_document_chunks INCLUDING ALL);
INSERT INTO ai_svc.ai_document_chunks SELECT * FROM public.ai_document_chunks ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.ai_document_chunks', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.ai_document_chunks), 1));
CREATE TABLE IF NOT EXISTS ai_svc.ai_documents (LIKE public.ai_documents INCLUDING ALL);
INSERT INTO ai_svc.ai_documents SELECT * FROM public.ai_documents ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.ai_documents', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.ai_documents), 1));
CREATE TABLE IF NOT EXISTS ai_svc.ai_messages (LIKE public.ai_messages INCLUDING ALL);
INSERT INTO ai_svc.ai_messages SELECT * FROM public.ai_messages ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.ai_messages', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.ai_messages), 1));
CREATE TABLE IF NOT EXISTS ai_svc.ai_models (LIKE public.ai_models INCLUDING ALL);
INSERT INTO ai_svc.ai_models SELECT * FROM public.ai_models ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.ai_models', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.ai_models), 1));
CREATE TABLE IF NOT EXISTS ai_svc.ai_quotas (LIKE public.ai_quotas INCLUDING ALL);
INSERT INTO ai_svc.ai_quotas SELECT * FROM public.ai_quotas ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.ai_quotas', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.ai_quotas), 1));
CREATE TABLE IF NOT EXISTS ai_svc.ai_usage_logs (LIKE public.ai_usage_logs INCLUDING ALL);
INSERT INTO ai_svc.ai_usage_logs SELECT * FROM public.ai_usage_logs ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.ai_usage_logs', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.ai_usage_logs), 1));
CREATE TABLE IF NOT EXISTS ai_svc.hermes_artifacts (LIKE public.hermes_artifacts INCLUDING ALL);
INSERT INTO ai_svc.hermes_artifacts SELECT * FROM public.hermes_artifacts ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.hermes_artifacts', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.hermes_artifacts), 1));
CREATE TABLE IF NOT EXISTS ai_svc.hermes_cluster_mcp_servers (LIKE public.hermes_cluster_mcp_servers INCLUDING ALL);
INSERT INTO ai_svc.hermes_cluster_mcp_servers SELECT * FROM public.hermes_cluster_mcp_servers ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.hermes_cluster_mcp_servers', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.hermes_cluster_mcp_servers), 1));
CREATE TABLE IF NOT EXISTS ai_svc.hermes_cluster_skills (LIKE public.hermes_cluster_skills INCLUDING ALL);
INSERT INTO ai_svc.hermes_cluster_skills SELECT * FROM public.hermes_cluster_skills ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.hermes_cluster_skills', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.hermes_cluster_skills), 1));
CREATE TABLE IF NOT EXISTS ai_svc.hermes_clusters (LIKE public.hermes_clusters INCLUDING ALL);
INSERT INTO ai_svc.hermes_clusters SELECT * FROM public.hermes_clusters ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.hermes_clusters', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.hermes_clusters), 1));
CREATE TABLE IF NOT EXISTS ai_svc.hermes_cron_jobs (LIKE public.hermes_cron_jobs INCLUDING ALL);
INSERT INTO ai_svc.hermes_cron_jobs SELECT * FROM public.hermes_cron_jobs ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.hermes_cron_jobs', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.hermes_cron_jobs), 1));
CREATE TABLE IF NOT EXISTS ai_svc.hermes_cron_runs (LIKE public.hermes_cron_runs INCLUDING ALL);
INSERT INTO ai_svc.hermes_cron_runs SELECT * FROM public.hermes_cron_runs ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.hermes_cron_runs', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.hermes_cron_runs), 1));
CREATE TABLE IF NOT EXISTS ai_svc.hermes_device_codes (LIKE public.hermes_device_codes INCLUDING ALL);
INSERT INTO ai_svc.hermes_device_codes SELECT * FROM public.hermes_device_codes ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.hermes_device_codes', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.hermes_device_codes), 1));
CREATE TABLE IF NOT EXISTS ai_svc.hermes_device_events (LIKE public.hermes_device_events INCLUDING ALL);
INSERT INTO ai_svc.hermes_device_events SELECT * FROM public.hermes_device_events ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.hermes_device_events', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.hermes_device_events), 1));
CREATE TABLE IF NOT EXISTS ai_svc.hermes_devices (LIKE public.hermes_devices INCLUDING ALL);
INSERT INTO ai_svc.hermes_devices SELECT * FROM public.hermes_devices ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.hermes_devices', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.hermes_devices), 1));
CREATE TABLE IF NOT EXISTS ai_svc.hermes_entitlements (LIKE public.hermes_entitlements INCLUDING ALL);
INSERT INTO ai_svc.hermes_entitlements SELECT * FROM public.hermes_entitlements ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.hermes_entitlements', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.hermes_entitlements), 1));
CREATE TABLE IF NOT EXISTS ai_svc.hermes_instances (LIKE public.hermes_instances INCLUDING ALL);
INSERT INTO ai_svc.hermes_instances SELECT * FROM public.hermes_instances ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.hermes_instances', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.hermes_instances), 1));
CREATE TABLE IF NOT EXISTS ai_svc.hermes_mcp_servers (LIKE public.hermes_mcp_servers INCLUDING ALL);
INSERT INTO ai_svc.hermes_mcp_servers SELECT * FROM public.hermes_mcp_servers ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.hermes_mcp_servers', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.hermes_mcp_servers), 1));
CREATE TABLE IF NOT EXISTS ai_svc.hermes_model_tokens (LIKE public.hermes_model_tokens INCLUDING ALL);
INSERT INTO ai_svc.hermes_model_tokens SELECT * FROM public.hermes_model_tokens ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.hermes_model_tokens', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.hermes_model_tokens), 1));
CREATE TABLE IF NOT EXISTS ai_svc.hermes_office_floors (LIKE public.hermes_office_floors INCLUDING ALL);
INSERT INTO ai_svc.hermes_office_floors SELECT * FROM public.hermes_office_floors ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.hermes_office_floors', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.hermes_office_floors), 1));
CREATE TABLE IF NOT EXISTS ai_svc.hermes_office_seats (LIKE public.hermes_office_seats INCLUDING ALL);
INSERT INTO ai_svc.hermes_office_seats SELECT * FROM public.hermes_office_seats ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.hermes_office_seats', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.hermes_office_seats), 1));
CREATE TABLE IF NOT EXISTS ai_svc.hermes_policies (LIKE public.hermes_policies INCLUDING ALL);
INSERT INTO ai_svc.hermes_policies SELECT * FROM public.hermes_policies ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.hermes_policies', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.hermes_policies), 1));
CREATE TABLE IF NOT EXISTS ai_svc.hermes_skills (LIKE public.hermes_skills INCLUDING ALL);
INSERT INTO ai_svc.hermes_skills SELECT * FROM public.hermes_skills ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.hermes_skills', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.hermes_skills), 1));
CREATE TABLE IF NOT EXISTS ai_svc.hermes_task_runs (LIKE public.hermes_task_runs INCLUDING ALL);
INSERT INTO ai_svc.hermes_task_runs SELECT * FROM public.hermes_task_runs ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.hermes_task_runs', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.hermes_task_runs), 1));
CREATE TABLE IF NOT EXISTS ai_svc.hermes_tasks (LIKE public.hermes_tasks INCLUDING ALL);
INSERT INTO ai_svc.hermes_tasks SELECT * FROM public.hermes_tasks ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.hermes_tasks', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.hermes_tasks), 1));
CREATE TABLE IF NOT EXISTS ai_svc.hermes_user_skills (LIKE public.hermes_user_skills INCLUDING ALL);
INSERT INTO ai_svc.hermes_user_skills SELECT * FROM public.hermes_user_skills ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ai_svc.hermes_user_skills', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ai_svc.hermes_user_skills), 1));

CREATE SCHEMA IF NOT EXISTS bpm_svc;
CREATE TABLE IF NOT EXISTS bpm_svc.bpm_callback_jobs (LIKE public.bpm_callback_jobs INCLUDING ALL);
INSERT INTO bpm_svc.bpm_callback_jobs SELECT * FROM public.bpm_callback_jobs ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('bpm_svc.bpm_callback_jobs', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM bpm_svc.bpm_callback_jobs), 1));
CREATE TABLE IF NOT EXISTS bpm_svc.bpm_cc_record (LIKE public.bpm_cc_record INCLUDING ALL);
INSERT INTO bpm_svc.bpm_cc_record SELECT * FROM public.bpm_cc_record ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('bpm_svc.bpm_cc_record', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM bpm_svc.bpm_cc_record), 1));
CREATE TABLE IF NOT EXISTS bpm_svc.bpm_process_definition (LIKE public.bpm_process_definition INCLUDING ALL);
INSERT INTO bpm_svc.bpm_process_definition SELECT * FROM public.bpm_process_definition ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('bpm_svc.bpm_process_definition', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM bpm_svc.bpm_process_definition), 1));
CREATE TABLE IF NOT EXISTS bpm_svc.bpm_process_instance (LIKE public.bpm_process_instance INCLUDING ALL);
INSERT INTO bpm_svc.bpm_process_instance SELECT * FROM public.bpm_process_instance ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('bpm_svc.bpm_process_instance', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM bpm_svc.bpm_process_instance), 1));
CREATE TABLE IF NOT EXISTS bpm_svc.bpm_process_log (LIKE public.bpm_process_log INCLUDING ALL);
INSERT INTO bpm_svc.bpm_process_log SELECT * FROM public.bpm_process_log ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('bpm_svc.bpm_process_log', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM bpm_svc.bpm_process_log), 1));
CREATE TABLE IF NOT EXISTS bpm_svc.bpm_task (LIKE public.bpm_task INCLUDING ALL);
INSERT INTO bpm_svc.bpm_task SELECT * FROM public.bpm_task ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('bpm_svc.bpm_task', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM bpm_svc.bpm_task), 1));

CREATE SCHEMA IF NOT EXISTS cc_svc;
CREATE TABLE IF NOT EXISTS cc_svc.cc_account_txns (LIKE public.cc_account_txns INCLUDING ALL);
INSERT INTO cc_svc.cc_account_txns SELECT * FROM public.cc_account_txns ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('cc_svc.cc_account_txns', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM cc_svc.cc_account_txns), 1));
CREATE TABLE IF NOT EXISTS cc_svc.cc_agents (LIKE public.cc_agents INCLUDING ALL);
INSERT INTO cc_svc.cc_agents SELECT * FROM public.cc_agents ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('cc_svc.cc_agents', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM cc_svc.cc_agents), 1));
CREATE TABLE IF NOT EXISTS cc_svc.cc_billing_accounts (LIKE public.cc_billing_accounts INCLUDING ALL);
INSERT INTO cc_svc.cc_billing_accounts SELECT * FROM public.cc_billing_accounts ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('cc_svc.cc_billing_accounts', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM cc_svc.cc_billing_accounts), 1));
CREATE TABLE IF NOT EXISTS cc_svc.cc_bills (LIKE public.cc_bills INCLUDING ALL);
INSERT INTO cc_svc.cc_bills SELECT * FROM public.cc_bills ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('cc_svc.cc_bills', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM cc_svc.cc_bills), 1));
CREATE TABLE IF NOT EXISTS cc_svc.cc_call_charges (LIKE public.cc_call_charges INCLUDING ALL);
INSERT INTO cc_svc.cc_call_charges SELECT * FROM public.cc_call_charges ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('cc_svc.cc_call_charges', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM cc_svc.cc_call_charges), 1));
CREATE TABLE IF NOT EXISTS cc_svc.cc_calls (LIKE public.cc_calls INCLUDING ALL);
INSERT INTO cc_svc.cc_calls SELECT * FROM public.cc_calls ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('cc_svc.cc_calls', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM cc_svc.cc_calls), 1));
CREATE TABLE IF NOT EXISTS cc_svc.cc_contacts (LIKE public.cc_contacts INCLUDING ALL);
INSERT INTO cc_svc.cc_contacts SELECT * FROM public.cc_contacts ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('cc_svc.cc_contacts', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM cc_svc.cc_contacts), 1));
CREATE TABLE IF NOT EXISTS cc_svc.cc_qc_keywords (LIKE public.cc_qc_keywords INCLUDING ALL);
INSERT INTO cc_svc.cc_qc_keywords SELECT * FROM public.cc_qc_keywords ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('cc_svc.cc_qc_keywords', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM cc_svc.cc_qc_keywords), 1));
CREATE TABLE IF NOT EXISTS cc_svc.cc_qc_results (LIKE public.cc_qc_results INCLUDING ALL);
INSERT INTO cc_svc.cc_qc_results SELECT * FROM public.cc_qc_results ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('cc_svc.cc_qc_results', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM cc_svc.cc_qc_results), 1));
CREATE TABLE IF NOT EXISTS cc_svc.cc_rates (LIKE public.cc_rates INCLUDING ALL);
INSERT INTO cc_svc.cc_rates SELECT * FROM public.cc_rates ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('cc_svc.cc_rates', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM cc_svc.cc_rates), 1));
CREATE TABLE IF NOT EXISTS cc_svc.cc_transcribe_jobs (LIKE public.cc_transcribe_jobs INCLUDING ALL);
INSERT INTO cc_svc.cc_transcribe_jobs SELECT * FROM public.cc_transcribe_jobs ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('cc_svc.cc_transcribe_jobs', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM cc_svc.cc_transcribe_jobs), 1));
CREATE TABLE IF NOT EXISTS cc_svc.cc_transcripts (LIKE public.cc_transcripts INCLUDING ALL);
INSERT INTO cc_svc.cc_transcripts SELECT * FROM public.cc_transcripts ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('cc_svc.cc_transcripts', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM cc_svc.cc_transcripts), 1));
CREATE TABLE IF NOT EXISTS cc_svc.cc_webhook_logs (LIKE public.cc_webhook_logs INCLUDING ALL);
INSERT INTO cc_svc.cc_webhook_logs SELECT * FROM public.cc_webhook_logs ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('cc_svc.cc_webhook_logs', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM cc_svc.cc_webhook_logs), 1));

CREATE SCHEMA IF NOT EXISTS crm_svc;
CREATE TABLE IF NOT EXISTS crm_svc.crm_assign_logs (LIKE public.crm_assign_logs INCLUDING ALL);
INSERT INTO crm_svc.crm_assign_logs SELECT * FROM public.crm_assign_logs ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('crm_svc.crm_assign_logs', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM crm_svc.crm_assign_logs), 1));
CREATE TABLE IF NOT EXISTS crm_svc.crm_contacts (LIKE public.crm_contacts INCLUDING ALL);
INSERT INTO crm_svc.crm_contacts SELECT * FROM public.crm_contacts ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('crm_svc.crm_contacts', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM crm_svc.crm_contacts), 1));
CREATE TABLE IF NOT EXISTS crm_svc.crm_contracts (LIKE public.crm_contracts INCLUDING ALL);
INSERT INTO crm_svc.crm_contracts SELECT * FROM public.crm_contracts ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('crm_svc.crm_contracts', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM crm_svc.crm_contracts), 1));
CREATE TABLE IF NOT EXISTS crm_svc.crm_customers (LIKE public.crm_customers INCLUDING ALL);
INSERT INTO crm_svc.crm_customers SELECT * FROM public.crm_customers ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('crm_svc.crm_customers', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM crm_svc.crm_customers), 1));
CREATE TABLE IF NOT EXISTS crm_svc.crm_followups (LIKE public.crm_followups INCLUDING ALL);
INSERT INTO crm_svc.crm_followups SELECT * FROM public.crm_followups ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('crm_svc.crm_followups', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM crm_svc.crm_followups), 1));
CREATE TABLE IF NOT EXISTS crm_svc.crm_leads (LIKE public.crm_leads INCLUDING ALL);
INSERT INTO crm_svc.crm_leads SELECT * FROM public.crm_leads ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('crm_svc.crm_leads', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM crm_svc.crm_leads), 1));
CREATE TABLE IF NOT EXISTS crm_svc.crm_opportunities (LIKE public.crm_opportunities INCLUDING ALL);
INSERT INTO crm_svc.crm_opportunities SELECT * FROM public.crm_opportunities ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('crm_svc.crm_opportunities', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM crm_svc.crm_opportunities), 1));
CREATE TABLE IF NOT EXISTS crm_svc.crm_opportunity_stage_logs (LIKE public.crm_opportunity_stage_logs INCLUDING ALL);
INSERT INTO crm_svc.crm_opportunity_stage_logs SELECT * FROM public.crm_opportunity_stage_logs ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('crm_svc.crm_opportunity_stage_logs', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM crm_svc.crm_opportunity_stage_logs), 1));
CREATE TABLE IF NOT EXISTS crm_svc.crm_payments (LIKE public.crm_payments INCLUDING ALL);
INSERT INTO crm_svc.crm_payments SELECT * FROM public.crm_payments ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('crm_svc.crm_payments', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM crm_svc.crm_payments), 1));
CREATE TABLE IF NOT EXISTS crm_svc.crm_pool_rules (LIKE public.crm_pool_rules INCLUDING ALL);
INSERT INTO crm_svc.crm_pool_rules SELECT * FROM public.crm_pool_rules ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('crm_svc.crm_pool_rules', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM crm_svc.crm_pool_rules), 1));

CREATE SCHEMA IF NOT EXISTS im_svc;
CREATE TABLE IF NOT EXISTS im_svc.im_agent_presence (LIKE public.im_agent_presence INCLUDING ALL);
INSERT INTO im_svc.im_agent_presence SELECT * FROM public.im_agent_presence ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS im_svc.im_agent_skills (LIKE public.im_agent_skills INCLUDING ALL);
INSERT INTO im_svc.im_agent_skills SELECT * FROM public.im_agent_skills ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('im_svc.im_agent_skills', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM im_svc.im_agent_skills), 1));
CREATE TABLE IF NOT EXISTS im_svc.im_conversations (LIKE public.im_conversations INCLUDING ALL);
INSERT INTO im_svc.im_conversations SELECT * FROM public.im_conversations ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('im_svc.im_conversations', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM im_svc.im_conversations), 1));
CREATE TABLE IF NOT EXISTS im_svc.im_kb_daily_stats (LIKE public.im_kb_daily_stats INCLUDING ALL);
INSERT INTO im_svc.im_kb_daily_stats SELECT * FROM public.im_kb_daily_stats ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('im_svc.im_kb_daily_stats', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM im_svc.im_kb_daily_stats), 1));
CREATE TABLE IF NOT EXISTS im_svc.im_kb_misses (LIKE public.im_kb_misses INCLUDING ALL);
INSERT INTO im_svc.im_kb_misses SELECT * FROM public.im_kb_misses ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('im_svc.im_kb_misses', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM im_svc.im_kb_misses), 1));
CREATE TABLE IF NOT EXISTS im_svc.im_messages (LIKE public.im_messages INCLUDING ALL);
INSERT INTO im_svc.im_messages SELECT * FROM public.im_messages ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('im_svc.im_messages', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM im_svc.im_messages), 1));
CREATE TABLE IF NOT EXISTS im_svc.im_quick_replies (LIKE public.im_quick_replies INCLUDING ALL);
INSERT INTO im_svc.im_quick_replies SELECT * FROM public.im_quick_replies ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('im_svc.im_quick_replies', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM im_svc.im_quick_replies), 1));
CREATE TABLE IF NOT EXISTS im_svc.im_sensitive_words (LIKE public.im_sensitive_words INCLUDING ALL);
INSERT INTO im_svc.im_sensitive_words SELECT * FROM public.im_sensitive_words ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('im_svc.im_sensitive_words', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM im_svc.im_sensitive_words), 1));
CREATE TABLE IF NOT EXISTS im_svc.im_sites (LIKE public.im_sites INCLUDING ALL);
INSERT INTO im_svc.im_sites SELECT * FROM public.im_sites ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('im_svc.im_sites', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM im_svc.im_sites), 1));
CREATE TABLE IF NOT EXISTS im_svc.im_skill_groups (LIKE public.im_skill_groups INCLUDING ALL);
INSERT INTO im_svc.im_skill_groups SELECT * FROM public.im_skill_groups ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('im_svc.im_skill_groups', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM im_svc.im_skill_groups), 1));
CREATE TABLE IF NOT EXISTS im_svc.im_visitors (LIKE public.im_visitors INCLUDING ALL);
INSERT INTO im_svc.im_visitors SELECT * FROM public.im_visitors ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('im_svc.im_visitors', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM im_svc.im_visitors), 1));

CREATE SCHEMA IF NOT EXISTS monitor_svc;
CREATE TABLE IF NOT EXISTS monitor_svc.monitor_alert_events (LIKE public.monitor_alert_events INCLUDING ALL);
INSERT INTO monitor_svc.monitor_alert_events SELECT * FROM public.monitor_alert_events ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('monitor_svc.monitor_alert_events', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM monitor_svc.monitor_alert_events), 1));
CREATE TABLE IF NOT EXISTS monitor_svc.monitor_alert_rules (LIKE public.monitor_alert_rules INCLUDING ALL);
INSERT INTO monitor_svc.monitor_alert_rules SELECT * FROM public.monitor_alert_rules ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('monitor_svc.monitor_alert_rules', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM monitor_svc.monitor_alert_rules), 1));
CREATE TABLE IF NOT EXISTS monitor_svc.monitor_metric_samples (LIKE public.monitor_metric_samples INCLUDING ALL);
INSERT INTO monitor_svc.monitor_metric_samples SELECT * FROM public.monitor_metric_samples ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('monitor_svc.monitor_metric_samples', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM monitor_svc.monitor_metric_samples), 1));
CREATE TABLE IF NOT EXISTS monitor_svc.ops_job_heartbeats (LIKE public.ops_job_heartbeats INCLUDING ALL);
INSERT INTO monitor_svc.ops_job_heartbeats SELECT * FROM public.ops_job_heartbeats ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('monitor_svc.ops_job_heartbeats', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM monitor_svc.ops_job_heartbeats), 1));
CREATE TABLE IF NOT EXISTS monitor_svc.scheduled_job_logs (LIKE public.scheduled_job_logs INCLUDING ALL);
INSERT INTO monitor_svc.scheduled_job_logs SELECT * FROM public.scheduled_job_logs ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('monitor_svc.scheduled_job_logs', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM monitor_svc.scheduled_job_logs), 1));
CREATE TABLE IF NOT EXISTS monitor_svc.scheduled_jobs (LIKE public.scheduled_jobs INCLUDING ALL);
INSERT INTO monitor_svc.scheduled_jobs SELECT * FROM public.scheduled_jobs ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('monitor_svc.scheduled_jobs', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM monitor_svc.scheduled_jobs), 1));

CREATE SCHEMA IF NOT EXISTS mp_svc;
CREATE TABLE IF NOT EXISTS mp_svc.channel_accounts (LIKE public.channel_accounts INCLUDING ALL);
INSERT INTO mp_svc.channel_accounts SELECT * FROM public.channel_accounts ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('mp_svc.channel_accounts', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM mp_svc.channel_accounts), 1));
CREATE TABLE IF NOT EXISTS mp_svc.mp_accounts (LIKE public.mp_accounts INCLUDING ALL);
INSERT INTO mp_svc.mp_accounts SELECT * FROM public.mp_accounts ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('mp_svc.mp_accounts', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM mp_svc.mp_accounts), 1));
CREATE TABLE IF NOT EXISTS mp_svc.mp_articles (LIKE public.mp_articles INCLUDING ALL);
INSERT INTO mp_svc.mp_articles SELECT * FROM public.mp_articles ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('mp_svc.mp_articles', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM mp_svc.mp_articles), 1));
CREATE TABLE IF NOT EXISTS mp_svc.mp_fan_sync_jobs (LIKE public.mp_fan_sync_jobs INCLUDING ALL);
INSERT INTO mp_svc.mp_fan_sync_jobs SELECT * FROM public.mp_fan_sync_jobs ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('mp_svc.mp_fan_sync_jobs', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM mp_svc.mp_fan_sync_jobs), 1));
CREATE TABLE IF NOT EXISTS mp_svc.mp_fans (LIKE public.mp_fans INCLUDING ALL);
INSERT INTO mp_svc.mp_fans SELECT * FROM public.mp_fans ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('mp_svc.mp_fans', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM mp_svc.mp_fans), 1));
CREATE TABLE IF NOT EXISTS mp_svc.mp_menus (LIKE public.mp_menus INCLUDING ALL);
INSERT INTO mp_svc.mp_menus SELECT * FROM public.mp_menus ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('mp_svc.mp_menus', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM mp_svc.mp_menus), 1));
CREATE TABLE IF NOT EXISTS mp_svc.mp_messages (LIKE public.mp_messages INCLUDING ALL);
INSERT INTO mp_svc.mp_messages SELECT * FROM public.mp_messages ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('mp_svc.mp_messages', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM mp_svc.mp_messages), 1));
CREATE TABLE IF NOT EXISTS mp_svc.mp_publish_result_jobs (LIKE public.mp_publish_result_jobs INCLUDING ALL);
INSERT INTO mp_svc.mp_publish_result_jobs SELECT * FROM public.mp_publish_result_jobs ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('mp_svc.mp_publish_result_jobs', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM mp_svc.mp_publish_result_jobs), 1));
CREATE TABLE IF NOT EXISTS mp_svc.post_publications (LIKE public.post_publications INCLUDING ALL);
INSERT INTO mp_svc.post_publications SELECT * FROM public.post_publications ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('mp_svc.post_publications', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM mp_svc.post_publications), 1));

CREATE SCHEMA IF NOT EXISTS pay_svc;
CREATE TABLE IF NOT EXISTS pay_svc.pay_callback_jobs (LIKE public.pay_callback_jobs INCLUDING ALL);
INSERT INTO pay_svc.pay_callback_jobs SELECT * FROM public.pay_callback_jobs ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('pay_svc.pay_callback_jobs', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM pay_svc.pay_callback_jobs), 1));
CREATE TABLE IF NOT EXISTS pay_svc.pay_channels (LIKE public.pay_channels INCLUDING ALL);
INSERT INTO pay_svc.pay_channels SELECT * FROM public.pay_channels ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('pay_svc.pay_channels', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM pay_svc.pay_channels), 1));
CREATE TABLE IF NOT EXISTS pay_svc.pay_notify_logs (LIKE public.pay_notify_logs INCLUDING ALL);
INSERT INTO pay_svc.pay_notify_logs SELECT * FROM public.pay_notify_logs ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('pay_svc.pay_notify_logs', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM pay_svc.pay_notify_logs), 1));
CREATE TABLE IF NOT EXISTS pay_svc.pay_orders (LIKE public.pay_orders INCLUDING ALL);
INSERT INTO pay_svc.pay_orders SELECT * FROM public.pay_orders ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('pay_svc.pay_orders', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM pay_svc.pay_orders), 1));
CREATE TABLE IF NOT EXISTS pay_svc.pay_refunds (LIKE public.pay_refunds INCLUDING ALL);
INSERT INTO pay_svc.pay_refunds SELECT * FROM public.pay_refunds ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('pay_svc.pay_refunds', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM pay_svc.pay_refunds), 1));

CREATE SCHEMA IF NOT EXISTS ticket_svc;
CREATE TABLE IF NOT EXISTS ticket_svc.ticket_events (LIKE public.ticket_events INCLUDING ALL);
INSERT INTO ticket_svc.ticket_events SELECT * FROM public.ticket_events ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ticket_svc.ticket_events', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ticket_svc.ticket_events), 1));
CREATE TABLE IF NOT EXISTS ticket_svc.ticket_notification_jobs (LIKE public.ticket_notification_jobs INCLUDING ALL);
INSERT INTO ticket_svc.ticket_notification_jobs SELECT * FROM public.ticket_notification_jobs ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ticket_svc.ticket_notification_jobs', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ticket_svc.ticket_notification_jobs), 1));
CREATE TABLE IF NOT EXISTS ticket_svc.ticket_tickets (LIKE public.ticket_tickets INCLUDING ALL);
INSERT INTO ticket_svc.ticket_tickets SELECT * FROM public.ticket_tickets ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('ticket_svc.ticket_tickets', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM ticket_svc.ticket_tickets), 1));

CREATE SCHEMA IF NOT EXISTS vis_svc;
CREATE TABLE IF NOT EXISTS vis_svc.vis_brands (LIKE public.vis_brands INCLUDING ALL);
INSERT INTO vis_svc.vis_brands SELECT * FROM public.vis_brands ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('vis_svc.vis_brands', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM vis_svc.vis_brands), 1));
CREATE TABLE IF NOT EXISTS vis_svc.vis_geo_prompts (LIKE public.vis_geo_prompts INCLUDING ALL);
INSERT INTO vis_svc.vis_geo_prompts SELECT * FROM public.vis_geo_prompts ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('vis_svc.vis_geo_prompts', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM vis_svc.vis_geo_prompts), 1));
CREATE TABLE IF NOT EXISTS vis_svc.vis_geo_results (LIKE public.vis_geo_results INCLUDING ALL);
INSERT INTO vis_svc.vis_geo_results SELECT * FROM public.vis_geo_results ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('vis_svc.vis_geo_results', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM vis_svc.vis_geo_results), 1));
CREATE TABLE IF NOT EXISTS vis_svc.vis_geo_runs (LIKE public.vis_geo_runs INCLUDING ALL);
INSERT INTO vis_svc.vis_geo_runs SELECT * FROM public.vis_geo_runs ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('vis_svc.vis_geo_runs', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM vis_svc.vis_geo_runs), 1));
CREATE TABLE IF NOT EXISTS vis_svc.vis_keywords (LIKE public.vis_keywords INCLUDING ALL);
INSERT INTO vis_svc.vis_keywords SELECT * FROM public.vis_keywords ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('vis_svc.vis_keywords', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM vis_svc.vis_keywords), 1));
CREATE TABLE IF NOT EXISTS vis_svc.vis_rank_snapshots (LIKE public.vis_rank_snapshots INCLUDING ALL);
INSERT INTO vis_svc.vis_rank_snapshots SELECT * FROM public.vis_rank_snapshots ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('vis_svc.vis_rank_snapshots', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM vis_svc.vis_rank_snapshots), 1));
CREATE TABLE IF NOT EXISTS vis_svc.vis_serp_tasks (LIKE public.vis_serp_tasks INCLUDING ALL);
INSERT INTO vis_svc.vis_serp_tasks SELECT * FROM public.vis_serp_tasks ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('vis_svc.vis_serp_tasks', 'id'), GREATEST((SELECT COALESCE(max(id), 1) FROM vis_svc.vis_serp_tasks), 1));

-- +goose Down
-- 回滚：删各 schema（public 副本保留）
DROP SCHEMA IF EXISTS ai_svc CASCADE;
DROP SCHEMA IF EXISTS bpm_svc CASCADE;
DROP SCHEMA IF EXISTS cc_svc CASCADE;
DROP SCHEMA IF EXISTS crm_svc CASCADE;
DROP SCHEMA IF EXISTS im_svc CASCADE;
DROP SCHEMA IF EXISTS monitor_svc CASCADE;
DROP SCHEMA IF EXISTS mp_svc CASCADE;
DROP SCHEMA IF EXISTS pay_svc CASCADE;
DROP SCHEMA IF EXISTS ticket_svc CASCADE;
DROP SCHEMA IF EXISTS vis_svc CASCADE;
