-- +goose Up
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS ai_conversations (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id bigint NOT NULL DEFAULT 0,
  title varchar(200) DEFAULT '',
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_ai_conversations_user_id ON ai_conversations (user_id);

CREATE TABLE IF NOT EXISTS ai_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  conversation_id bigint NOT NULL REFERENCES ai_conversations (id) ON DELETE CASCADE,
  role varchar(20) NOT NULL DEFAULT '',
  content text,
  created_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_ai_messages_conversation_id ON ai_messages (conversation_id);

CREATE TABLE IF NOT EXISTS ai_documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title varchar(200) DEFAULT '',
  content text,
  uploader_id bigint NOT NULL DEFAULT 0,
  chunk_count int NOT NULL DEFAULT 0,
  created_at timestamptz(3) DEFAULT NULL,
  updated_at timestamptz(3) DEFAULT NULL,
  PRIMARY KEY (id)
);

-- The embedding column is intentionally dimensionless (pgvector allows it):
-- v1 does exact cosine scans without a vector index, so switching embedding
-- models or dimensions never requires a schema change.
CREATE TABLE IF NOT EXISTS ai_document_chunks (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  document_id bigint NOT NULL REFERENCES ai_documents (id) ON DELETE CASCADE,
  chunk_index int NOT NULL DEFAULT 0,
  content text,
  embedding vector,
  PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_ai_document_chunks_document_id ON ai_document_chunks (document_id);

INSERT INTO menus (id,name,title,icon,path,component,parent_id,sort,status,hidden,permission,created_at,updated_at) VALUES
(900,'ai','AI 智能','control-platform','/ai','Layout',0,3,1,0,'',NOW(),NOW()),
(901,'ai-assistant','AI 助手','chat','/ai/assistant','ai/assistant/index',900,1,1,0,'',NOW(),NOW()),
(902,'ai-knowledge','知识库','data-base','/ai/knowledge','ai/knowledge/index',900,2,1,0,'',NOW(),NOW())
ON CONFLICT DO NOTHING;

SELECT setval(pg_get_serial_sequence('menus','id'), (SELECT COALESCE(MAX(id),1) FROM menus));

-- +goose Down
DELETE FROM menus WHERE id IN (900,901,902);

SELECT setval(pg_get_serial_sequence('menus','id'), (SELECT COALESCE(MAX(id),1) FROM menus));

DROP TABLE IF EXISTS ai_document_chunks;
DROP TABLE IF EXISTS ai_documents;
DROP TABLE IF EXISTS ai_messages;
DROP TABLE IF EXISTS ai_conversations;

-- The vector extension is intentionally kept on Down: other consumers may
-- depend on it and dropping extensions is an operator decision.
